services:
  - type: web
    name: moodify-sentiment-api
    env: python
    buildCommand: "pip install -r moodify_backend_fastapi/requirements.txt"
    startCommand: "uvicorn moodify_backend_fastapi/sentiment_analysis_and_chunking.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        value: DATABASE_URL
      - key: OPENAI_API_KEY
        value: OPENAI_API_KEY

